import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "서울, 오늘의 문화 | 요즘 전시",
  // description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
