import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./component/NavBar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "서울, 오늘의 문화",
  // description: "Generated by create next app",
};

declare global {
  interface Window {
    naver: any;
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head>
        <script
          type="text/javascript"
          src="https://oapi.map.naver.com/openapi/v3/maps.js?ncpClientId=<%=process.env.NEXT_PUBLIC_MAP_CLIENT_ID%>"
        ></script>
      </head>
      <body>{children}</body>
    </html>
  );
}
