import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./_component/NavBar";
import RecoilRootProvider from "./_component/RecoilRootProvider";
import Script from "next/script";

export const metadata: Metadata = {
  title: "서울, 오늘의 문화",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head></head>
      <body>
        <NavBar />
        <RecoilRootProvider>{children}</RecoilRootProvider>{" "}
        <Script
          type="text/javascript"
          strategy="beforeInteractive"
          src={`https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NEXT_PUBLIC_MAP_CLIENT_ID}`}
        />
      </body>
    </html>
  );
}
