import type { Metadata } from "next";
import Script from "next/script";

declare global {
  interface Window {
    naver: any;
  }
}

export const metadata: Metadata = {
  title: "서울, 오늘의 문화",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Script
        type="text/javascript"
        src={`https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NEXT_PUBLIC_MAP_CLIENT_ID}`}
      />
      {children}
    </>
  );
}
